### ISSUE TITLE
Criar página para ideias das próximas talks

### ISSUE THREAD

**Issue by andreymoser** [node-poa/Meetups#14]
Criar página colaborativa para que todos coloquem ideias e talks que gostariam de ver, assuntos interessantes, exemplos de bibliotecas, etc... 

Exemplo:
+ [https://github.com/sydney-node-ninjas/meetup/wiki/Talk-ideas](https://github.com/sydney-node-ninjas/meetup/wiki/Talk-ideas)

**Comment by jeanbauer** [comment]
A ideia desta página seria usar como node-poa.github.io?

**Comment by hmschreiner** [comment]
Não exatamente. Seria como o link que o @andreymoser colocou como exemplo.
