### ISSUE TITLE
6º Meetup @ Ilegra - 11/07 - Call for Papers

### ISSUE THREAD

**Issue by hmschreiner** [node-poa/Meetups#15]
Tem algum conteúdo bacana para apresentar no meetup? Leu um artigo interessante e gostaria de compartilhar sua opinião? Resolveu um bug no trabalho e quer apresentar a solução? **Todos são bem vindos para compartilhar conhecimento!**

Por favor, informe estes dados quando mandar uma proposta:
- Título da talk
- Resumo da talk
- Nível de conhecimento
  - Básico
  - Intermediário
  - Avançado
- Categoria da talk
  - Palestra (30 minutos)
  - Lightning talk (20 minutos)
  - Ignite talk (5 minutos)
  - Fishbowl (30 minutos)
- Fale um pouco sobre você
- Nome da Empresa/Faculdade/Instituição 
- Cargo/Posição
- Redes sociais (Twitter, Facebook, etc.)

***Como entrar em contato?***

+ Comenta aqui nesta issue seu interesse **OU**
+ Nos envie uma mensagem privada no [Meetup](https://www.meetup.com/pt-BR/Node-js-Porto-Alegre-Meetup) **OU**
+ Nos envie uma **DM** no [Twitter](https://twitter.com/nodejspoa)

**Comment by jacksonfdam** [comment]
👍

**Comment by MuriloEduardo** [comment]
Encerrou já?

**Comment by hmschreiner** [comment]
Ainda não, @MuriloEduardo. Estamos começando, na verdade! 😄

**Comment by alexrochas** [comment]
Medindo a saúde da minha aplicação com RxJS

Contextualização e breve introdução ao RxJS e apresentação de case de como foi usado para coletar eventos e calcular a saúde da aplicação em um intervalo de tempo.

Nível Intermediário

Palestra 30 min

Sou formado em análise de sistemas pela Uniritter, faixa preta de karatê e trabalho como desenvolvedor a pelo menos 10 anos, a maior parte do tempo com Java, Ruby e Python. No ultimo ano tenho estudado e trabalhado com Nodejs.

Engenheiro de Software na Ilegra

https://www.facebook.com/alex.rocha.88
http://alexrochas.github.io/

**Comment by hmschreiner** [comment]
Valeu, @alexrochas!

**Comment by szanata** [comment]
## Log de Ciclo de Vida de Requests

Em uma aplicação **node/express**: Como logar _breadcrumbs_ e informações em diferentes momentos de uma mesma **request** sem contaminá-los com _logs_ de outras _requests_ acontecendo em paralelo, assim isolando atomicamente todos os _logs_ do ciclo de vida dela.

**Nível**: Avançado

**Keywords**: Stack trace, logging, tick, event emitter, atomic logs

**Sobre mim**: Sou desenvolvedor a 11 anos (5 com js), e designer. Atualmente trabalho para a empresa Meltwater.

[github.com/madeinstefano](http://github.com/madeinstefano)
[szanata.com](http://szanata.com)

**Comment by hmschreiner** [comment]
Valeu, @madeinstefano!

**Comment by waldemarnt** [comment]
**Título da talk**:  2 coisas que todo desenvolvedor Node.js deve saber
**Resumo da talk**: Nesta talk vamos fazer um deep dive em dois conceitos core do Node.js, que são: Event Loop e Modulos.
**Nível de conhecimento**: Intermediario
**Categoria da talk**: Palestra
**Fale um pouco sobre você**:
Waldemar Neto é autor do livro [Construindo APIs testáveis com Node.js](https://leanpub.com/construindo-apis-testaveis-com-nodejs/), Engenheiro de software na Meltwater, apaixonado por boas práticas e qualidade de software além de contribuidor opensource e apoiador da comunidade brasileira.

**Twitter**: @waldemarnt
**Blog**: [http://walde.co](http://walde.co)

**Comment by thiagodorneles** [comment]
**Título:** Thinking in GraphQL
**Resumo:** Contextualizar o GraphQL analisando os problemas atuais no modo de implementação do protocolo REST.
Introduzir conceitos do GraphQL,  mudar nosso mindset, mostrar como utilizar,  prós e contras quando colocado na prática.
**Nível:** Intermediário
**Categoria:** Lightning Talk
**Fale um pouco sobre você:** Trabalho com desenvolvimento há uns 10 anos. Atuando no back e front durante todo esse tempo, porém com maior foco no back. Maior parte do tempo trabalhei com C#, mas nos últimos anos trabalho maior parte do tempo com NodeJS.
**Empresa atual:** Superplayer
**Cargo:** Software Engineer
**Twitter:** @thiagodorneles


Não sei se ainda dá tempo para submeter, mas qualquer coisa já fica para a próxima

**Comment by hmschreiner** [comment]
E aí @thiagodorneles! A agenda para este meetup já está completa, mas com certeza tu já é o primeiro palestrante confirmado para o próximo! 😄 

Valeu!
