### ISSUE TITLE
7º Meetup @ ThoughtWorks - 23/08/2017 - Call for Papers

### ISSUE THREAD

**Issue by hmschreiner** [node-poa/Meetups#16]
Tem algum conteúdo bacana para apresentar no meetup? Leu um artigo interessante e gostaria de compartilhar sua opinião? Resolveu um bug no trabalho e quer apresentar a solução? **Todos são bem vindos para compartilhar conhecimento!**

Por favor, informe estes dados quando mandar uma proposta:
- Título da talk
- Resumo da talk
- Nível de conhecimento
  - Básico
  - Intermediário
  - Avançado
- Categoria da talk
  - Palestra (30 minutos)
  - Lightning talk (20 minutos)
  - Ignite talk (5 minutos)
  - Fishbowl (30 minutos)
- Fale um pouco sobre você
- Nome da Empresa/Faculdade/Instituição 
- Cargo/Posição
- Redes sociais (Twitter, Facebook, etc.)

***Como entrar em contato?***

+ Comenta aqui nesta issue seu interesse **OU**
+ Nos envie uma mensagem privada no [Meetup](https://www.meetup.com/pt-BR/Node-js-Porto-Alegre-Meetup) **OU**
+ Nos envie uma **DM** no [Twitter](https://twitter.com/nodejspoa)

**Comment by awerlang** [comment]
Conforme prometido, segue minha proposta sobre o módulo `cluster`.

**Título da talk:** Multi-processos no node.js (título provisório)
**Resumo da talk:** Sabemos que o node.js executa um thread único em _userland_. Vamos conhecer como utilizar o módulo nativo cluster para aproveitar melhor os recursos do sistema, e aprender como criar serviços mais robustos. Instanciação de processos, crash recovery, comunicação.
**Nível de conhecimento:** Intermediário
**Categoria da talk:** Palestra (30 minutos)
**Fale um pouco sobre você**
Bebo café, escrevo código, crio bugs, resolvo problemas há mais de 15 anos, não necessariamente neste ordem. Há 3 anos criando produtos com JavaScript.
**Redes sociais (Twitter, Facebook, etc.):** 
Twitter: @awerlang
GitHub: @awerlang

**Comment by hmschreiner** [comment]
Valeu @awerlang! 💯

**Comment by thiagodorneles** [comment]
**Título:** Thinking in GraphQL
**Resumo:** Contextualizar o GraphQL analisando os problemas atuais no modo de implementação do protocolo REST.
Introduzir conceitos do GraphQL,  mudar nosso mindset, mostrar como utilizar,  prós e contras quando colocado na prática.
**Nível:** Intermediário
**Categoria:** Lightning Talk
**Fale um pouco sobre você:** Trabalho com desenvolvimento há uns 10 anos. Atuando no back e front durante todo esse tempo, porém com maior foco no back. Maior parte do tempo trabalhei com C#, mas nos últimos anos trabalho maior parte do tempo com NodeJS.
**Empresa atual:** Superplayer
**Cargo:** Software Engineer
**Twitter:**  [@thiagodorneles](https://twitter.com/thiagodorneles)

**Comment by hmschreiner** [comment]
Valeu, @thiagodorneles! 😃

**Comment by jonatasfreitasv** [comment]
**Título:** Cross Platform Desktop App's with Electron
**Resumo:** Apresentação do framework Electron com hello world, arquitetura básica e show case de grandes empresas/aplicações utilizando este framework.
**Nível:** Básico/Intermediário
**Categoria:** Lightning Talk
**Fale um pouco sobre você:** Trabalho com desenvolvimento há uns 15 anos. Atuando como fullstack, com foco atualmente em Data Science.
**Empresa atual:** Zenvia
**Cargo:** Senior Developer / Data Scientist
**Github:** @jonatasfreitasv

**Comment by jmurowaniecki** [comment]
**Título da talk:** NPM - _com M de man-in-the-middle_
**Resumo da talk**: Expor e debater vulnerabilidades do sistema de gerenciamento de dependências em ambientes diversos sem nos aprofundarmos na dor ou técnicas de exploração.
**Nível de conhecimento**: Básico / Intermediário.
**Categoria da talk**: **Ignite** / Lightning Talk.

**Fale um pouco sobre você:**
_john@PLANOcc:/dev/juniorzão # whoami_
> Desenvolvedor apaixonado por tecnologia, performance e padrões em tratamento de TOC.
> #JS #Python #C #PHP #Clipper #Security

Twitter: [♠J](https://twitter.com/0xD3C0d3)
Medium: [John Murowaniecki](https://medium.com/@jmurowaniecki)

**Comment by thiagodorneles** [comment]
@hmschreiner Eu vou ter que cancelar minha participação no evento. Terei que dar um curso bem nesse dia.

**Comment by hmschreiner** [comment]
Que pena, @thiagodorneles. Tua palestra fica no backlog para o próximo! 😃

**Comment by maxdevjs** [comment]
Talks interessantes, espero fiquem disponíveis em vídeo.

P.S.: achei dois "bugs" na issue, o link para o Twitter de @awerlang e @thiagodorneles

**Comment by hmschreiner** [comment]
@max-devjs vai ter live streaming no YouTube do evento! Pode acompanhar por lá!
