### ISSUE TITLE
8º Meetup @ e-Core - 10/10/2017 - Call for Papers

### ISSUE THREAD

**Issue by andreymoser** [node-poa/Meetups#18]
Tem algum conteúdo bacana para apresentar no meetup? Leu um artigo interessante e gostaria de compartilhar sua opinião? Resolveu um bug no trabalho e quer apresentar a solução? **Todos são bem vindos para compartilhar conhecimento!**

Por favor, informe estes dados quando mandar uma proposta:
- Título da talk
- Resumo da talk
- Nível de conhecimento
  - Básico
  - Intermediário
  - Avançado
- Categoria da talk
  - Palestra (30 minutos)
  - Lightning talk (20 minutos)
  - Ignite talk (5 minutos)
  - Fishbowl (30 minutos)
- Fale um pouco sobre você
- Nome da Empresa/Faculdade/Instituição 
- Cargo/Posição
- Redes sociais (Twitter, Facebook, etc.)

***Como entrar em contato?***

+ Comenta aqui nesta issue seu interesse **OU**
+ Nos envie uma mensagem privada no [Meetup](https://www.meetup.com/pt-BR/Node-js-Porto-Alegre-Meetup) **OU**
+ Nos envie uma **DM** no [Twitter](https://twitter.com/nodejspoa)

**Comment by andreymoser** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Criar call for papers 8o Meetup](https://trello.com/c/7BREziqn/3-criar-call-for-papers-8o-meetup)

**Comment by andreymoser** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Melhorar call for papers](https://trello.com/c/V7UST1JG/5-melhorar-call-for-papers)

**Comment by hmschreiner** [comment]
O Call for Papers está aqui agora: https://nodejspoa.typeform.com/to/b2Vp0L
