### ISSUE TITLE
Próximos Meetups - Planejamento 2018

### ISSUE THREAD

**Issue by andreymoser** [node-poa/Meetups#19]
Galera, já está na hora de começar o planejamento dos meetups de 2018, segue abaixo um rascunho da proposta:

- 9º Meetup - Março/Abril - Local a definir
- 10º Meetup - Maio/Junho - Local a definir
- 11º Meetup - Agosto/Setembro - Local a definir
- 12º Meetup - Outubro/Novembro - Local a definir

A ideia é colher feedbacks da comunidade, alinhar com parceiros sobre local e patrocínios, o que é essencial para termos um 2018 repleto de meetups! 🚀

**Comment by hmschreiner** [comment]
Planejamento movido para o Trello.
