### ISSUE TITLE
5º Meetup @ e-Core 16/05/2017 - Call for Papers

### ISSUE THREAD

**Issue by andreymoser** [node-poa/Meetups#9]
Tens interesse em apresentar algo em JavaScript e/ou Node.js? Entre em contato conosco, sinta-se a vontade. :smiley: 

Por favor, informe estes dados quando mandar uma proposta:
- Título da talk
- Resumo da talk
- Nível de conhecimento
  - Básico
  - Intermediário
  - Avançado
- Categoria da talk
  - Palestra (30 minutos)
  - Lightning talk (20 minutos)
  - Ignite talk (5 minutos)
  - Fishbowl (30 minutos)
- Fale um pouco sobre você
- Nome da Empresa/Faculdade/Instituição 
- Redes sociais (Twitter, Facebook, etc.)

***Como entrar em contato?***

+ Comenta aqui nesta issue seu interesse **OU**
+ Nos envie uma mensagem privada no [Meetup](https://www.meetup.com/pt-BR/Node-js-Porto-Alegre-Meetup) **OU**
+ Nos envie uma direct message no [Twitter](https://twitter.com/nodejspoa)

**Comment by marceloserpa** [comment]
Eu estou muito interessado em apresentar sobre testes de contrato. Quero abordar bem o conceito e mostrar uns códigos de exemplo =)

**Comment by hmschreiner** [comment]
Muito legal, @marceloserpa! Poderia nos dar mais detalhes sobre a tua palestra? Dá uma olhada no comentário do @andreymoser com os dados que a gente precisa!

**Comment by marceloserpa** [comment]
Eae pessoal, segue abaixo os dados da apresentação:

**Título da talk:** Defenda seus consumidores! Use testes de contrato.

**Resumo da talk:** O desenvolvimento de APIs tem ganhado muito espaço nos últimos anos.  Uma das maiores vantagens das APIs é possibilitar que diferentes sistemas consumam as mesmas funcionalidades. Nessa talk irei abordar o que são contratos e porque devemos testá-los para evitar que nossos consumidores sejam quebrados.

**Nível de conhecimento:** Intermediário

**Categoria da talk:** Lightning talk (20 minutos)

Olá eu sou Marcelo, formado em análise e desenvolvimento de sistemas na FTEC. Sou desenvolvedor de software na Ilegra, atualmente trabalho com desenvolvimento de microserviços. Tenho experiência em Java8, Spring Boot, Camel e Kafka. No meu tempo livre brinco bastante com NodeJS, React e outras coisas \o/

**Empresa:** Ilegra
**Faculdade:** FTEC

**Comment by andreymoser** [comment]
Valeu @marceloserpa!

**Comment by renanbastos93** [comment]
Estou interessado em aprender mais compartilhar conhecimentos, quem sabe até ensina alguém. Porém sou mero aprendiz, mas sei que os foda aprende com os noob e os noob aprende com os foda. 
Enfim, quero ajudar.

**Comment by hmschreiner** [comment]
@renanbastos93 toda ajuda é bem vinda. Todos nós estamos aprendendo uns com os outros e esta é exatamente a ideia. Tu podes apresentar qualquer coisa de teu interesse que envolva Node e Javascript. Pode ser qualquer coisa mesmo:
- Leu um artigo bacana e quer comentar sobre?
- Resolveu um problema novo no trabalho e quer mostrar a solução?
- Tá testando uma library/framework/metodologia e quer falar sobre o que está achando?

Só manda tua proposta! 😄

**Comment by renanbastos93** [comment]
@hmschreiner Opa, beleza mas nunca palestrei sou tri envergonhado pra esse tipo de coisa, mas vou ver se bolo algo então.

**Comment by hmschreiner** [comment]
@renanbastos93 sempre tem a primeira vez! 😄 
Se por acaso não quiseres ou não se sentir confortável pra palestrar, podes ajudar divulgando pra gurizada e incentivar o pessoal a participar dos eventos.

**Comment by waldemarnt** [comment]
Minha talk

**Por dentro dos Módulos no Node.js**

Módulos são uma das coisas mais interessantes do Node.js. Nessa talk vamos conhecer como os módulos funcionam e como podemos tirar maior proveito deles em nossas aplicações.

**Nivel de conhecimento**: básico

Lightning talk (20 minutos)

**Comment by MuriloEduardo** [comment]
Fala rapaziada!
Tenho 2 anos de **NodeJs** na bagagem e até hoje tenho MUITA dificuldade para fazer deploy de produção em Servidores VPS Compartilhados, como: Google Clound Plataform por exemplo.

Se alguém tiver algo para falar sobre, ajudaria a mim e acredito que à outros também.

Forte abraço a todos, e até o próximo Meetup.

**Comment by hmschreiner** [comment]
Boa, @MuriloEduardo! Obrigado pela sugestão. Vamos tentar encaixar este assunto nos próximos meetups.

**Comment by mwebler** [comment]
Eai galera, gostaria de propor uma talk sobre o [Node-RED](https://nodered.org/), uma ferramenta que estou usando no meu TCC.

**Título da talk**: Conectando APIs, serviços e IoT com Node-RED

**Resumo da talk:** O Node-RED é uma ferramenta de desenvolvimento de aplicações criado para conectar serviços, APIs e dispositivos de IoT. Desenvolvido em cima do NodeJS, ele disponibiliza um editor gráfico baseado no fluxo de dados para a criação de aplicações. Nessa talk irei abordar como o Node-RED funciona e as suas possíveis aplicações.

**Nível de conhecimento**: Básico

**Categoria da talk**: Lightning talk (20 minutos)

Eu sou o Matheus Webler, formando de ciência da computação pela Unisinos nesse semestre e desenvolvedor na SAP, em São Leopoldo.

**Comment by hmschreiner** [comment]
Que bacana, @mwebler! Seja muito bem vindo! 😄

**Comment by joaoricardo15** [comment]
Eae galera!

Gostaria propor um talk sobre uma plataforma para internet das coisas que estou desenvolvendo com algumas ferramentas Node.js
 

Resumo da talk: Estou implementando uma plataforma  de internet das coisas em que utilizo um broker de comunicação desenvolvido em Node.js. Além disso estou utilizando um SDK do Azure (serviço de nuvem da Microsoft) que fornece comunicação com seu hub internet das coisas. Acredito que o Node tem grande potencial para desenvolvimento de aplicaçaões internet das coisas - o simples fato de existirem ferramentas como essas que estou trabalhando evidenciam esse fato - e por isso acho que esse é um bom tema para se discutir.

Nível de conhecimento: Básico

Categoria da talk: Lightning talk (20 minutos)

Me chamo João Ricardo Cardoso, sou aluno de Engenharia de Controle e Automação da UFRGS e entusiasta em tecnologia. Atualmente sou estagiário na Elipse Software, onde desenvolvo sistemas voltados à indústria 4.0

**Comment by hmschreiner** [comment]
Valeu, @joaoricardo15! Qual seria o título da talk?

**Comment by joaoricardo15** [comment]
Título: Node.js como ferramenta de desenvolvimento para aplicações internet das coisas

Que tal? 😊

**Comment by hmschreiner** [comment]
Boa, @joaoricardo15! Vou te mandar uma mensagem pelo Meetup para confirmar a tua palestra.

**Comment by szanata** [comment]
Boa noite, tudo certo?
Gostaria de apresentar sobre:

**Título da talk:** Sincronização de código com Promises + Generators
**Resumo da talk:** Como tornar código js mais legível e evitar o *Callback Hell* através de do uso de Generators e Promises do ES6. Tudo sem transpilers.
**Nível de conhecimento:** Avançado
**Categoria da talk:** Lightning talk

*Sobre mim*
Sou Stéfano Zanata, dev da Meltwater News, empresa norueguesa de inteligência de mídia.
Formado em Sistema de Informação, atualmente cursando Design de Produto.
Contato atráves do contato@szanata.com ou via github https://github.com/madeinstefano

Abraços

**Comment by hmschreiner** [comment]
Que beleza, @madeinstefano. Tu acabou de fechar a grade de palestrantes! hehe! 😄
